### ISSUE TITLE
WLAN app crashes on Pixel 3a with Android 9 Pie

### ISSUE THREAD

**Issue by jimmy-yilong-li** [bastibl/android-wlan#1]
Hi guys,

I installed the WLAN into a Google Pixel 3a installed Android 9 Pie but it can't open and shows no response. Do you have the same issue?

PS: I successfully compiled toolchain provided by Bastian and really appreciate his great work. The [BXX firmware loader](https://github.com/bastibl/android-hw) works properly.

**Comment by bastibl** [comment]
What exactly do you mean? Does it crash, does the application close, or do you see the plot but do not receive any frames?

**Comment by jimmy-yilong-li** [comment]
> What exactly do you mean? Does it crash, does the application close, or do you see the plot but do not receive any frames?

Hi, it juts crashed and didn't open. I didn't see any UI or plot.

**Comment by jimmy-yilong-li** [comment]
> What exactly do you mean? Does it crash, does the application close, or do you see the plot but do not receive any frames?

Hi @bastibl,

Thanks for your help. I just copied the error information via logcat of android-wlan project on my Pixel 3a.

2020-07-14 03:39:43.239 13744-13744/net.bastibl.wlan E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.bastibl.wlan, PID: 13744
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libgnuradio-runtime.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at net.bastibl.wlan.MainActivity.<clinit>(MainActivity.kt:280)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2869)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Does it mean lack of a library?

**Comment by bastibl** [comment]
This is really strange... The only thing I could imagine is that the app finds the library during build, but doesn't find it while packaging the APK. Can you check that the symlink in the toolchain folder is working, i.e., if `gnuradio-android/toolchain/jni` has symlinks to the lib folders.
By default, the app only builds the 64bit version, but that shouldn't be an issue for the Pixel 3a

**Comment by chod5072** [comment]
Hi all,

I think that I have run into the same issue that @JimmyLi-Network  has encountered. Using guradio-android (awesome project, many thanks!) I have installed android-hw, FM, and WLAN,  applications onto a pixel 3a running android 11. I have been able to use android-FM with an RTL-SDR (attempted with B200). The android-hw application seems to be working as i get "B200 firmaware loaded" messages a bit after its plugged in. I have also placed the USRP firmware in the gnuradio folder as directed. When i run the WLAN applications the screen flashes white and the applications promptly crashes. Attached is the log cat and my attempt to verify the libgnuradio-runtime.so is where it should be. Any help would be appreciated.

################################################################################
logcat android-WLAN
################################################################################
2020-12-06 00:59:31.009 12542-12542/? I/et.bastibl.wla: Late-enabling -Xcheck:jni
2020-12-06 00:59:31.042 12542-12542/? I/et.bastibl.wla: Unquickening 12 vdex files!
2020-12-06 00:59:31.124 12542-12542/net.bastibl.wlan W/ActivityThread: Application net.bastibl.wlan is waiting for the debugger on port 8100...
2020-12-06 00:59:31.126 12542-12542/net.bastibl.wlan I/System.out: Sending WAIT chunk
2020-12-06 00:59:46.800 12542-12542/net.bastibl.wlan I/System.out: Debugger has connected
2020-12-06 00:59:46.801 12542-12542/net.bastibl.wlan I/System.out: waiting for debugger to settle...
2020-12-06 00:59:47.017 12542-12542/net.bastibl.wlan I/System.out: waiting for debugger to settle...
2020-12-06 00:59:47.258 12542-12542/net.bastibl.wlan I/System.out: waiting for debugger to settle...
2020-12-06 00:59:48.313 12542-12542/net.bastibl.wlan I/chatty: uid=10295(net.bastibl.wlan) identical 5 lines
2020-12-06 00:59:48.526 12542-12542/net.bastibl.wlan I/System.out: waiting for debugger to settle...
2020-12-06 00:59:48.766 12542-12542/net.bastibl.wlan I/System.out: debugger has settled (1502)
2020-12-06 00:59:48.793 12542-12542/net.bastibl.wlan D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2020-12-06 00:59:49.219 12542-12542/net.bastibl.wlan D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-12-06 00:59:49.239 12542-12542/net.bastibl.wlan D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-12-06 00:59:49.861 12542-12542/net.bastibl.wlan D/AndroidRuntime: Shutting down VM
2020-12-06 00:59:49.916 12542-12542/net.bastibl.wlan E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.bastibl.wlan, PID: 12542
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libgnuradio-runtime.so" not found: needed by /data/app/~~-gPUty_ok7N9ozcEq3wILg==/net.bastibl.wlan-dz_CiiLAjtZi8VMurG0PFA==/base.apk!/lib/arm64-v8a/libnative-lib.so in namespace classloader-namespace
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at net.bastibl.wlan.MainActivity.<clinit>(MainActivity.kt:280)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2020-12-06 00:59:49.980 12542-12542/net.bastibl.wlan I/Process: Sending signal. PID: 12542 SIG: 9

################################################################################
checking gnuradio-android/toolchain/jni 
################################################################################.

android@numb-X570:~/src/gnuradio-android/toolchain/jni$ ls -la
total 8
drwxr-xr-x 2 android android 4096 Nov  4 18:39 .
drwxr-xr-x 1 android android 4096 Nov  4 18:39 ..
lrwxrwxrwx 1 android android   16 Nov  4 18:39 arm64-v8a -> ../arm64-v8a/lib
lrwxrwxrwx 1 android android   18 Nov  4 18:39 armeabi-v7a -> ../armeabi-v7a/lib

android@numb-X570:~/src/gnuradio-android/toolchain/jni$ ls ../arm64-v8a/lib/libgnuradio-runtime.so -la
-rw-r--r-- 1 android android 31290368 Nov  4 19:10 ../arm64-v8a/lib/libgnuradio-runtime.so

**Comment by bastibl** [comment]
Can you check if these paths match your directory structure:
https://github.com/bastibl/android-wlan/blob/master/app/build.gradle#L46

**Comment by chod5072** [comment]
@bastibl thank you for the help. Checking the path showed that it was indeed incorrect. I updated the jni path in my build.gradle file to match the working path in android-FM, shown below. Andoird-WLAN is now running successfully on my pixle 3a! 

`
'../../gnuradio-android/toolchain/jni'`

**Comment by bastibl** [comment]
Yay, great news. Thanks for the feedback :-)
